
const university = [
  {
    universityName: "University of Ibadan",
    location: "Ibadan",
    type:"Federal",
    website: "https://ui.edu.ng",
    email: "registrar@ui.edu.ng",
    phone: +234810324681031,
    address: "6 BenueRoad,University ofIbadan, P. O.Box 22133,UIPO, Ibadan,Nigeria.",
    programmes:[
               
                                  "Medicine and Surgery",
                                  "Dentistry",
                                  "Physiotherapy",
                                  "Biochemistry",
                                  "Physiology",
                                  "Human Nutrition and Dietetics",
                                  "Nursing Science",
                                  "Medical Laboratory Science",
                                  "Environmental Health Science",
                                   "Pharmacy",
                                  "Agricultural Economics",
                                  "Agricultural Extension and Rural Development",
                                  "Agronomy",
                                  "Animal Science",
                                  "Crop Protection and Environmental Biology",
                                  "Fisheries and Wildlife Management",
                                  "Forest Resources Management",
                                  "Aquaculture and Fisheries Management",
                                  "Wildlife and Ecotourism Management",
                                  "Social and Environmental Forestry",
                                  "Arabic Language and Literature",
                                  "Islamic Studies",
                                  "Archaeology (Single and Combined Honours)",
                                  "Anthropology Classics",
                                  "Religious Studies",
                                  "Communication and Language Arts",
                                  "Linguistics and African Languages (Linguistics, Yoruba, Igbo)",
                                  "History",
                                  "English Language and Literature",
                                  "Philosophy",
                                  "European Studies (French, Russian,German)",
                                  "Theatre Arts",
                                  "Law (LL.B.)",
                                  "Veterinary Medicine",
                                  "Agricultural and Environmental Engineering",
                                  "Civil Engineering",
                                  "Industrial and Production Engineering",
                                  "Petroleum Engineering",
                                  "Electrical and Electronics Engineering",
                                  "Mechanical Engineering",
                                  "Food Technology",
                                  "Wood Products Engineering",
                                  "Automotive Engineering",
                                  "Economics",
                                  "Geography",
                                  "Political Science",
                                  "Psychology",
                                  "Sociology",
                                  "Adult Education",
                                  "Educational Management",
                                  "Teacher Education (Arts, Social Sciences, Science, Pre-Primary Education)",
                                  "Special Education",
                                  "Human Kinetics",
                                  "Health Education",
                                  "Guidance and Counselling",
                                  "Library Studies",
                                  "Early Childhood Education",
                                  "Educational Evaluation",
                                  "Educational Psychology",
                                  "Archaeology (Single and Combined Honours)",
                                  "Anthropology",
                                  "Chemistry",
                                  "Industrial Chemistry",
                                  "Geography",
                                  "Computer Science",
                                  "Geology",
                                  "Mathematics",
                                  "Physics",
                                  "Statistics",
                                  "Zoology",
                                  "Btany",
                                  "Microbiology",
                ],
   
    requirements:           [  "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                                "For Direct Entry Admission:",
                                "Candidates must select UTME subject combinations specific to their chosen programme.",
                                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                            ],
    notes: ""
  },
  {
    universityName: "University of Lagos",
    location: "Lagos",
    type:"Federal",
    website: "https://unilag.edu.ng",
    email: "info@unilag.edu.ng",
    phone: +2348021234567,
    address: "University of Lagos, Akoka, Yaba, Lagos, Nigeria",

    programmes:[
             
                "Biomedical Engineering",
                "Chemical & Petroleum Engineering",
                "Civil & Environmental Engineering",
                "Computer Engineering",
                "Electrical & Electronics Engineering",
                "Mechanical Engineering",
                "Metallurgical & Materials Engineering",
                "Surveying & Geoinformatics Engineering",
                "Systems Engineering",
                "Architecture",
                "Building",
                "Estate Management",
                "Quantity Surveying",
                "Urban & Regional Planning",
                "Law (LL.B.)",
                "Accounting",
                "Actuarial Science",
                "Insurance",
                "Business Administration",
                "Finance",
                "Industrial Relations & Personnel",
                "Management (IRPM)",
                "Pharmacy",
                "Botany",
                "Cell Biology & Genetics",
                "Chemistry",
                "Computer Science",
                "Geology",
                "Geophysics",
                "Marine Biology",
                "Fisheries",
                "Mathematics",
                "Industrial Mathematics",
                "Statistics",
                "Microbiology",
                "Physics",
                "Zoology",
                "Economics",
                "Geography",
                "Mass Communication",
                "Political Science",
                "Psychology",
                "Social Work",
                "Sociology",
                "Accounting",
                "Banking and Finance",
                "Business Administration",
                "Demography and Social Statistics",
                "Economics",
                "Industrial Relations and Human Resource",
                "Management",
                "International Relations",
                "Management Information System",
                "Marketing",
                "Mass Communication",
                "Policy and Strategic Studies",
                "Political Science",
                "Psychology",
                "Sociology"
                                  
                       ],
    requirements:  [            
                    "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                    "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                    "For Direct Entry Admission:",
                    "Candidates must select UTME subject combinations specific to their chosen programme.",
                    "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                    "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                    ],
    notes: ""
  },

  {
    universityName: "Covenant University",
    location: "Ota",
    type:"Private",
    website: "https://covenantuniversity.edu.ng",
    email: "info@covenantuniversity.edu.ng",
    phone: +2342012273500,
    address: "Km 10, Idiroko Road, CanaanLand, Oya,Ogun state, Nigeria",
    programmes:[

            "Electronic & Electrical Engineering",
            "Mechanical Engineering",
            "Civil Engineering",
            "Chemical Engineering",
            "Metallurgical & Materials Engineering",
            "Food Engineering / Food Science & Technology",
            "Agricultural & Environmental Engineering",
            "Computer Engineering",
            "Computer Science with Mathematics",
            "Computer Science with Economics",
            "Aerospace Engineering",
            "Architecture",
            "Biochemistry",
            "Biology (Applied Biology and Biotechnology)",
            "Building Technology",
            "Chemical Engineering",
            "Computer Science",
            "Estate Management",
            "Industrial Chemistry",
            "Industrial Mathematics",
            "Industrial Physics with Applied Geophysics",
            "Industrial Physics with Electronics and IT Application",
            "Industrial Physics with Renewable Energy",
            "Information and Communication Engineering",
            "Microbiology",
            "Petroleum Engineering",
            "Biochemistry",
            "Botany",
            "Chemistry",
            "Industrial Chemistry",
            "Geology",
            "Applied Geophysics",
            "Mathematics",
            "Statistics",
            "Microbiology",
            "Physics / Engineering Physics",
            "Zoology",
            "Medicine (MBBS)",
            "Dentistry",
            "Nursing Sciences",
            "Medical Rehabilitation",
            "Pharmacy",
            "Economics",
            "Demography & Social Statistics",
            "Geography",
            "Political Science",
            "Psychology",
            "Sociology & Anthropology",
            "Entrepreneurship & Industrial Extension",
            "Mass Communication",
            "Film Production",
            "Broadcast Journalism",
            "Information Science & Media Studies",
                                  
          ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },

  {
    universityName: "Obafemi Awolowo University",
    location: "Ile-Ife",
    type:"Federal",
    website: "https://oauife.edu.ng",
    email: "info@oauife.edu.ng",
    phone: +2348104563456,
    address: "",
    programmes:[
             
                                    "Animal Science",
                                    "Crop Production & Protection",
                                    "Agricultural Economics",
                                    "Agricultural Extension & Rural Development",
                                    "Soil Science & Land Resources",
                                    "Management",
                                    "Consumer Sciences",
                                    "Dramatic Arts",
                                    "English",
                                    "Literature in English",
                                    "French",
                                    "German",
                                    "Portuguese",
                                    "History",
                                    "Yoruba",
                                    "Linguistics",
                                    "Music",
                                    "Philosophy",
                                    "Religious Studies",
                                  "International Relations",
                                    "Local Government Studies",
                                    "Management & Accounting",
                                    "Business Administration",
                                    "Public Administration",
                                    "Architecture",
                                  "Building",
                                  "Surveying & Geoinformatics",
                                  "Quantity Surveying",
                                  "Urban & Regional Planning",
                                  "Estate Management",
                                  "Fine & Applied Arts",
                                  "LL.B. (Law)",
                                   "History Education",
                                    "English Education",
                                    "Fine & Applied Arts Education",
                                    "French Education",
                                    "Language Arts Education",
                                    "Music Education",
                                    "Physical & Health Education",
                                    "Religious Studies Education",
                                    "Yoruba Education",
                                   "Biology Education",
                                    "Chemistry Education",
                                    "Mathematics Education",
                                    "Integrated Science Education",
                                    "Physics Education",
                                    "Economics Education",
                                    "Geography Education",
                                    "Guidance & Counselling",
                                    "Accountancy / Accounting",
                                    "Actuarial Science",
                                    "Agricultural Engineering",
                                    "Agricultural Science and Education",
                                    "Agriculture",
                                    "Anatomy",
                                    "Arabic Studies",
                                    "Archaeology",
                                    "Architecture",
                                    "Automotive Engineering",
                                    "Banking and Finance",
                                    "Biochemistry",
                                    "Biological Science(s)",
                                    "Botany",
                                    "Building",
                                    "Business Administration",
                                    "Business Education",
                                    "Chemical Engineering",
                                    "Chemistry",
                                    "Civil Engineering",
                                    "Civil Law",
                                    "Computer Engineering",
                                    "Computer Science",
                                    "Dentistry And Dental Surgery",
                                    "Drama / Dramatic / Performing Arts",
                                    "Economics",
                                    "Education and Arabic",
                                    "Education and Biology",
                                    "Education and Chemistry",
                                    "Education and Christian Religious Studies",
                                    "Education and Computer Science",
                                    "Education and Geography",
                                    "Education and Hausa",
                                    "Education and Integrated Science",
                                    "Education and Islamic Studies",
                                    "Education and Language Arts",
                                    "Education and Mathematics",
                                    "Education and Physics",
                                    "Education and Religious Studies",
                                    "Education and Social Studies",
                                    "Educational Administration and Planning",
                                    "Electrical And Computer Engineering",
                                    "Electrical Engineering",
                                    "English Language",
                                    "Fine Art",
                                    "Fisheries and Aquaculture",
                                    "Forestry And Wildlife Management",
                                    "French",
                                    "Geography",
                                    "Geology",
                                    "Glass Technology",
                                    "Guidance and Counseling",
                                    "Hausa",
                                    "Health Education",
                                    "History",
                                    "Home Economics and Education",
                                    "Human Kinetics",
                                    "Industrial Design",
                                    "Insurance",
                                    "International Studies",
                                    "Islamic / Sharia Law",
                                    "Library and Information Science",
                                    "Literature in English",
                                    "Local Government And Development Studies",
                                    "Marketing",
                                    "Mass Communication",
                                    "Mathematics",
                                    "Mechanical Engineering",
                                    "Mechatronics Engineering",
                                    "Medical Laboratory Science",
                                    "Medicine and Surgery",
                                    "Metallurgical Engineering",
                                    "Microbiology",
                                    "Mining Engineering",
                                    "Nursing / Nursing Science",
                                    "Pharmacy",
                                    "Physical and Health Education",
                                    "Physics",
                                    "Physiology",
                                    "Political Science",
                                    "Public Administration",
                                    "Quantity Surveying",
                                    "Radiography",
                                    "Sociology",
                                    "Statistics",
                                    "Surveying and Geo-Informatics",
                                    "Telecommuniction Engineering",
                                    "Textile Science and Technology",
                                    "Textile Science and Technology",
                                    "Theatre And Performing Arts",
                                    "Urban and Regional Planning",
                                    "Veterinary Medicine",
                                    "Water Resources and Environmental Engr.",
                                    "Zoology",
                                    "Land Surveying",
                                    "Agricultural Extention",
                                    "Adult Education and Community Development",
                                    "Accountancy / Accounting",
                                    "Adult Education",
                                    "Agricultural and Bio-Resources Engineering",
                                    "Agricultural Economics",
                                    "Agricultural Science and Education",
                                    "Agriculture",
                                    "Animal Science",
                                    "Archaeology",
                                    "Architecture",
                                    "Arts (Combined Honours)",
                                    "Banking and Finance",
                                    "Biochemistry",
                                    "Biological Science(s)",
                                    "Botany",
                                    "Business Education",
                                    "Business Management",
                                    "Civil Engineering",
                                    "Computer Education",
                                    "Computer Science",
                                    "Computer with Statistics",
                                    "Creative Arts",
                                    "Crop Science",
                                    "Dentistry And Dental Surgery",
                                    "Early Childhood Education",
                                    "Economics",
                                    "Education and Biology",
                                    "Education and Chemistry",
                                    "Education and Economics",
                                    "Education and English Language",
                                    "Education Fine and Applied Arts",
                                    "Education and French",
                                    "Education and Geography",
                                    "Education and History",
                                    "Education and Igbo",
                                    "Education and Integrated Science",
                                    "Education and Mathematics",
                                    "Education and Music",
                                    "Education and Physics",
                                    "Education and Political Science",
                                    "Education and Religious Studies",
                                    "Education and Science",
                                    "Education and Social Science",
                                    "Education and Social Studies",
                                    "Education Arts",
                                    "Electrical Engineering",
                                    "Electronics Engineering",
                                    "English and Literary Studies",
                                    "Estate Management",
                                    "Fine Art / Fine and Applied Arts",
                                    "Food Science and Technology",
                                    "Food Science and Technology",
                                    "French",
                                    "French with German / Russian",
                                    "Geography",
                                    "Geology",
                                    "German",
                                    "Guidance and Counseling",
                                    "Health Education",
                                    "History",
                                    "Home Economics and Education",
                                    "Home Science",
                                    "Human Anatomy",
                                    "Industrial Technical Education",
                                    "Law",
                                    "Library and Information Science",
                                    "Linguistics",
                                    "Linguistics, Igbo and other African Languages",
                                    "Marketing",
                                    "Mass Communication",
                                    "Mathematics",
                                    "Mechanical Engineering",
                                    "Medical Laboratory Science",
                                    "Medical Rehabilitation",
                                    "Medicine and Surgery",
                                    "Metallurgical and Material Engineering",
                                    "Microbiology",
                                    "Music",
                                    "Nursing / Nursing Science",
                                    "Nutrition and Dietetics",
                                    "Pharmacy",
                                    "Philosophy",
                                    "Physical Education",
                                    "Physics",
                                    "Physics / Astrology",
                                    "Physiology",
                                    "Political Science",
                                    "Political Science",
                                    "Primary Education Studies",
                                    "Psychology",
                                    "Public Administration And Local Government",
                                    "Pure / Applied Chemistry",
                                    "Pure and Industrial Chemistry",
                                    "Radiography",
                                    "Religious Studies",
                                    "Russian",
                                    "Science Laboratory Technology",
                                    "Social Works",
                                    "Sociology and Anthropology",
                                    "Soil Science",
                                    "Special Education",
                                    "Statistics",
                                    "Surveying and Geo-Informatics",
                                    "Surveying And Geoinformatics",
                                    "Teacher Education Science",
                                    "Theatre And Film Studies",
                                    "Urban and Regional Planning",
                                    "Veterinary Medicine",
                                    "Zoology",
                                    "Public Administration and Local Govt",
                                    "Modern Languages B.A. (Single and Combined Hons)",
                                    "Accounting",
                                    "Adult Education",
                                    "Agricultural Science and Education",
                                    "Agriculture",
                                    "Anatomy",
                                    "Applied Geophysics",
                                    "Arabic Studies",
                                    "Architecture",
                                    "Biochemistry",
                                    "Biomedical Engineering",
                                    "Business Administration",
                                    "Business Education",
                                    "Chemical Engineering",
                                    "Chemistry",
                                    "Civil Engineering",
                                    "Common and Islamic Law",
                                    "Common Law",
                                    "Comparative Religious Studies",
                                    "Computer Engineering",
                                    "Computer Science",
                                    "Criminology And Security Studies",
                                    "Economics",
                                    "Education and Arabic",
                                    "Education and Biology",
                                    "Education and Chemistry",
                                    "Education and Christian Religious Studies",
                                    "Education and Computer Science",
                                    "Education and Economics",
                                    "Education and English Language",
                                    "Education and French",
                                    "Education and Geography",
                                    "Education and History",
                                    "Education and Islamic Studies",
                                    "Education and Mathematics",
                                    "Education and Physics",
                                    "Education and Social Studies",
                                    "Education and Yoruba",
                                    "Educational Management",
                                    "Educational Technology / Introductory",
                                    "Technology",
                                    "Electrical / Electronics Engineering",
                                    "English Language",
                                    "Estate Management",
                                    "Finance",
                                    "Fisheries and Aquaculture",
                                    "Food Engineering",
                                    "Food Science",
                                    "Forestry And Wildlife Management",
                                    "French",
                                    "Geography and Environmental Management",
                                    "Geology",
                                    "Hausa",
                                    "Economics",
                                    "Geography",
                                    "Mass Communication",
                                    "Political Science",
                                    "Psychology",
                                    "Social Work",
                                    "Sociology",
                                    "Accounting",
                                    "Banking and Finance",
                                    "Business Administration",
                                    "Demography and Social Statistics",
                                    "Economics",
                                    "Industrial Relations and Human Resource",
                                    "Management",
                                    "International Relations",
                                    "Management Information System",
                                    "Marketing",
                                    "Mass Communication",
                                    "Policy and Strategic Studies",
                                    "Political Science",
                                    "Psychology",
                                    "Sociology"
                                 
                       ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: 0
  },
    {
    universityName: "University of Ilorin",
    location: "Ilorin",
    type:"Federal",
    website: "https://unilorin.edu.ng",
    email: "registrar@unilorin.edu.ng",
    phone: +2348050878080,
    address: "P.M.B. 1515, Ilorin,",
    programmes:[
              
                                  "Health Education",
                                  "History and International Studies",
                                  "Home Economics",
                                  "Human Kinetics",
                                  "Igbo",
                                  "Industrial Chemistry",
                                  "Industrial Relations and Personnel",
                                  "Management",
                                  "Information And Communication Science",
                                  "Islamic Studies",
                                  "Library and Information Science",
                                  "Linguistics",
                                  "Marketing",
                                  "Mass Communication",
                                  "Mathematics",
                                  "Mechanical Engineering",
                                  "Medical Laboratory Science",
                                  "Medicine and Surgery",
                                  "Metallurgical and Material Engineering",
                                  "Microbiology",
                                  "Nursing / Nursing Science",
                                  "Optometry",
                                  "Performing Arts",
                                  "Pharmacy",
                                  "Physics",
                                  "Physiology",
                                  "Physiotherapy",
                                  "Plant Biology",
                                  "Political Science",
                                  "Primary Education Studies",
                                  "Psychology",
                                  "Public Administration",
                                  "Quantity Surveying",
                                  "Social Works",
                                  "Sociology",
                                  "Statistics",
                                  "Surveying and Geo-Informatics",
                                  "Surveying And Geoinformatics",
                                  "Teacher Education Science",
                                  "Technical Education",
                                  "Technology Education",
                                  "Telecommunication Science",
                                  "Urban and Regional Planning",
                                  "Veterinary Medicine",
                                  "Water Resources and Environmental Engr.",
                                  "Yoruba",
                                  "Zoology",
                                  "Agricultural And Biosystems Engineering",
                                  "Metalwork Technology Education",
                                  "Electrical / Electronics Technology Education",
                                  "Building Technology Education",
                                  "Doctor of Pharmacy",
                               
    ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
  {
    universityName: "FUT Minna",
    location: "Minna",
    type:"Federal",
    website: "https://futminna.edu.ng",
    email: "registrar@futminna.edu.ng",
    phone: +2347035862582,
    address: "Federal University of Technology, Minna (FUTMinna) Main Campus, Gidan Kwanu P.M.B. 65, Minna, Niger State, Nigeria",
    programmes:[
                  "Accounting",
                  "Actuarial Science",
                  "Adult Education",
                  "Adult Education / Economics and Statistics",
                  "Adult Education / English Literature",
                  "Adult Education / Geography and Regional",
                  "Planning",
                  "Adult Education / Political Science and Public",
                  "Administration",
                  "Agricultural Economics",
                  "Agricultural Engineering",
                  "Agricultural Science and Education",
                  "Agriculture",
                  "Anatomy",
                  "Animal and Environmental Biology",
                  "Animal Biology and Environment",
                  "Animal Science",
                  "Applied Geophysics",
                  "Architecture",
                  "Banking and Finance",
                  "Biochemistry",
                  "Botany",
                  "Business Administration",
                  "Business Administration",
                  "Business Education",
                  "Chemical Engineering",
                  "Chemistry",
                  "Civil Engineering",
                  "Computer Education",
                  "Computer Engineering",
                  "Computer Science",
                  "Dentistry And Dental Surgery",
                  "Drama / Dramatic / Performing Arts",
                  "Early Childhood Education",
                  "Economics and Statistics",
                  "Education and Biology",
                  "Education and Chemistry",
                  "Education and Computer Science",
                  "Education and Economics",
                  "Education and Edo Language",
                  "Education and English Language and Literature",
                  "Education Fine and Applied Arts",
                  "Education and French",
                  "Education and Geography",
                  "Education and History",
                  "Education and Integrated Science",
                  "Education and Mathematics",
                  "Education and Physics",
                  "Education and Political Science",
                  "Education and Religious Studies",
                  "Education and Social Studies",
                  "Educational Administration",
                  "Educational Management",
                  "Electrical / Electronics Engineering",
                  "English Language and Literature",
                  "Entrepreneurship",
                  "Environmental Education",
                  "Environmental Management And Toxicology",
                  "Estate Management",
                  "Fine Art / Fine and Applied Arts",
                  "Fisheries",
                  "Forestry And WildLife",
                  "French",
                  "Geography and Regional Planning",
                  "Geography and Regional Planning",
                  "Geology",
                  "Guidance and Counseling",
                  "Health Education",
                  "History",
                  "Home Economics and Education",
                  "Human Kinetics",
                  "Industrial Chemistry",
                  "Industrial Mathematics",
                  "Industrial Physics",
                  "Industrial Relations and Personnel",
                  "Management",
                  "Industrial Technical Education",
                  "Insurance",
                  "International Studies and Diplomacy",
                  "International Studies and Diplomacy",
                  "Languages and Linguistics",
                  "Law",
                  "Library and Information Science",
                  "Linguistics / Edo",
                  "Marine Engineering",
                  "Marketing",
                  "Mass Communication",
                  "Mathematics",
                  "Mathematics and Economics",
                  "Mechanical Engineering",
                  "Mechatronics Engineering",
                  "Medical Biochemistry",
                  "Medical Laboratory Science",
                  "Medicine and Surgery",
                  "Metallurgical and Material Engineering",
                  "Microbiology",
                  "Music",
                  "Nursing / Nursing Science",
                  "Optometry",
                  "Petroleum Engineering",
                  "Pharmacy",
                  "Philosophy",
                  "Physical Education",
                  "Physics",
                  "Physics / Industrial Physics",
                  "Physiology",
                  "Physiotherapy",
                  "Plant Science and Biotechnology",
                  "Political Science",
                  "Political Science and Public Administration",
                  "Production Engineering",
                  "Public Administration",
                  "Pure / Applied Mathematics",
                  "Quantity Surveying",
                  "Radiography",
                  "Religious Studies",
                  "Science Laboratory Technology",
                  "Secretarial Administration and Education",
                  "Secretarial Education",
                  "Social Works",
                  "Sociology and Anthropology",
                  "Soil Science",
                  "Special Education",
                  "Statistics",
                  "Structural Engineering",
                  "Surveying and Geo-Informatics",
                  "Taxation",
                  "Technical Education",
                  "Theatre Arts",
                  "Veterinary Medicine",
              ],
    requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },

  {
    universityName: "Ahmadu Bello University",
    location: "Zaria",
    type:"Federal",
    website: "https://abu.edu.ng",
    email: "",
    phone: +234,
    address: "",
    programmes:[
                 "Accountancy / Accounting",
                  "Actuarial Science",
                  "Agricultural Engineering",
                  "Agricultural Science and Education",
                  "Agriculture",
                  "Anatomy",
                  "Arabic Studies",
                  "Archaeology",
                  "Architecture",
                  "Automotive Engineering",
                  "Banking and Finance",
                  "Biochemistry",
                  "Biological Science(s)",
                  "Botany",
                  "Building",
                  "Business Administration",
                  "Business Administration",
                  "Business Education",
                  "Chemical Engineering",
                  "Chemistry",
                  "Civil Engineering",
                  "Civil Law",
                  "Computer Engineering",
                  "Computer Science",
                  "Dentistry And Dental Surgery",
                  "Drama / Dramatic / Performing Arts",
                  "Economics",
                  "Education and Arabic",
                  "Education and Biology",
                  "Education and Chemistry",
                  "Education and Christian Religious Studies",
                  "Education and Computer Science",
                  "Education and Geography",
                  "Education and Hausa",
                  "Education and Integrated Science",
                  "Education and Islamic Studies",
                  "Education and Language Arts",
                  "Education and Mathematics",
                  "Education and Physics",
                  "Education and Religious Studies",
                  "Education and Social Studies",
                  "Educational Administration and Planning",
                  "Electrical And Computer Engineering",
                  "Electrical Engineering",
                  "English Language",
                  "Fine Art",
                  "Fisheries and Aquaculture",
                  "Forestry And Wildlife Management",
                  "French",
                  "Geography",
                  "Geology",
                  "Glass Technology",
                  "Guidance and Counseling",
                  "Hausa",
                  "Health Education",
                  "History",
                  "Home Economics and Education",
                  "Human Kinetics",
                  "Industrial Design",
                  "Insurance",
                  "International Studies",
                  "Islamic / Sharia Law",
                  "Library and Information Science",
                  "Literature in English",
                  "Local Government And Development Studies",
                  "Marketing",
                  "Mass Communication",
                  "Mathematics",
                  "Mechanical Engineering",
                  "Mechatronics Engineering",
                  "Medical Laboratory Science",
                  "Medicine and Surgery",
                  "Metallurgical Engineering",
                  "Microbiology",
                  "Mining Engineering",
                  "Nursing / Nursing Science",
                  "Pharmacy",
                  "Physical and Health Education",
                  "Physics",
                  "Physiology",
                  "Political Science",
                  "Public Administration",
                  "Quantity Surveying",
                  "Radiography",
                  "Sociology",
                  "Statistics",
                  "Surveying and Geo-Informatics",
                  "Telecommuniction Engineering",
                  "Textile Science and Technology",
                  "Textile Science and Technology",
                  "Theatre And Performing Arts",
                  "Urban and Regional Planning",
                  "Veterinary Medicine",
                  "Water Resources and Environmental Engr.",
                  "Zoology",
                  "Land Surveying",
                  "Agricultural Extention",
                  "Adult Education and Community Development",

              ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
   {
    universityName: "University of Nigeria",
    location: "Nsukka",
    type:"Federal",
    website: "https://unn.edu.ng",
    email: "",
    phone: +234,
    address: "",
    programmes:[
                 "Accountancy / Accounting",
                  "Adult Education",
                  "Agricultural and Bio-Resources Engineering",
                  "Agricultural Economics",
                  "Agricultural Science and Education",
                  "Agriculture",
                  "Animal Science",
                  "Archaeology",
                  "Architecture",
                  "Arts (Combined Honours)",
                  "Banking and Finance",
                  "Biochemistry",
                  "Biological Science(s)",
                  "Botany",
                  "Business Education",
                  "Business Management",
                  "Civil Engineering",
                  "Computer Education",
                  "Computer Science",
                  "Computer with Statistics",
                  "Creative Arts",
                  "Crop Science",
                  "Dentistry And Dental Surgery",
                  "Early Childhood Education",
                  "Economics",
                  "Education and Biology",
                  "Education and Chemistry",
                  "Education and Economics",
                  "Education and English Language",
                  "Education Fine and Applied Arts",
                  "Education and French",
                  "Education and Geography",
                  "Education and History",
                  "Education and Igbo",
                  "Education and Integrated Science",
                  "Education and Mathematics",
                  "Education and Music",
                  "Education and Physics",
                  "Education and Political Science",
                  "Education and Religious Studies",
                  "Education and Science",
                  "Education and Social Science",
                  "Education and Social Studies",
                  "Education Arts",
                  "Electrical Engineering",
                  "Electronics Engineering",
                  "English and Literary Studies",
                  "Estate Management",
                  "Fine Art / Fine and Applied Arts",
                  "Food Science and Technology",
                  "Food Science and Technology",
                  "French",
                  "French with German / Russian",
                  "Geography",
                  "Geology",
                  "German",
                  "Guidance and Counseling",
                  "Health Education",
                  "History",
                  "Home Economics and Education",
                  "Home Science",
                  "Human Anatomy",
                  "Industrial Technical Education",
                  "Law",
                  "Library and Information Science",
                  "Linguistics",
                  "Linguistics, Igbo and other African Languages",
                  "Marketing",
                  "Mass Communication",
                  "Mathematics",
                  "Mechanical Engineering",
                  "Medical Laboratory Science",
                  "Medical Rehabilitation",
                  "Medicine and Surgery",
                  "Metallurgical and Material Engineering",
                  "Microbiology",
                  "Music",
                  "Nursing / Nursing Science",
                  "Nutrition and Dietetics",
                  "Pharmacy",
                  "Philosophy",
                  "Physical Education",
                  "Physics",
                  "Physics / Astrology",
                  "Physiology",
                  "Political Science",
                  "Political Science",
                  "Primary Education Studies",
                  "Psychology",
                  "Public Administration And Local Government",
                  "Pure / Applied Chemistry",
                  "Pure and Industrial Chemistry",
                  "Radiography",
                  "Religious Studies",
                  "Russian",
                  "Science Laboratory Technology",
                  "Social Works",
                  "Sociology and Anthropology",
                  "Soil Science",
                  "Special Education",
                  "Statistics",
                  "Surveying and Geo-Informatics",
                  "Surveying And Geoinformatics",
                  "Teacher Education Science",
                  "Theatre And Film Studies",
                  "Urban and Regional Planning",
                  "Veterinary Medicine",
                  "Zoology",
                  "Public Administration and Local Govt",
                  "Modern Languages B.A. (Single and Combined Hons)"


              ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
  {
    universityName: "University of Benin",
    location: "Benin City",
    type:"Federal",
    website: "https://uniben.edu",
    email: "",
    phone: +234,
    address: "",
    programmes:[
                 "Accounting",
                  "Actuarial Science",
                  "Adult Education",
                  "Adult Education / Economics and Statistics",
                  "Adult Education / English Literature",
                  "Adult Education / Geography and Regional Planning",
                  "Adult Education / Political Science and Public Administration",
                  "Agricultural Economics",
                  "Agricultural Engineering",
                  "Agricultural Science and Education",
                  "Agriculture",
                  "Anatomy",
                  "Animal and Environmental Biology",
                  "Animal Biology and Environment",
                  "Animal Science",
                  "Applied Geophysics",
                  "Architecture",
                  "Banking and Finance",
                  "Biochemistry",
                  "Botany",
                  "Business Administration",
                  "Business Administration",
                  "Business Education",
                  "Chemical Engineering",
                  "Chemistry",
                  "Civil Engineering",
                  "Computer Education",
                  "Computer Engineering",
                  "Computer Science",
                  "Dentistry And Dental Surgery",
                  "Drama / Dramatic / Performing Arts",
                  "Early Childhood Education",
                  "Economics and Statistics",
                  "Education and Biology",
                  "Education and Chemistry",
                  "Education and Computer Science",
                  "Education and Economics",
                  "Education and Edo Language",
                  "Education and English Language and Literature",
                  "Education Fine and Applied Arts",
                  "Education and French",
                  "Education and Geography",
                  "Education and History",
                  "Education and Integrated Science",
                  "Education and Mathematics",
                  "Education and Physics",
                  "Education and Political Science",
                  "Education and Religious Studies",
                  "Education and Social Studies",
                  "Educational Administration",
                  "Educational Management",
                  "Electrical / Electronics Engineering",
                  "English Language and Literature",
                  "Entrepreneurship",
                  "Environmental Education",
                  "Environmental Management And Toxicology",
                  "Estate Management",
                  "Fine Art / Fine and Applied Arts",
                  "Fisheries",
                  "Forestry And WildLife",
                  "French",
                  "Geography and Regional Planning",
                  "Geography and Regional Planning",
                  "Geology",
                  "Guidance and Counseling",
                  "Health Education",
                  "History",
                  "Home Economics and Education",
                  "Human Kinetics",
                  "Industrial Chemistry",
                  "Industrial Mathematics",
                  "Industrial Physics",
                  "Industrial Relations and Personnel Management",
                  "Industrial Technical Education",
                  "Insurance",
                  "International Studies and Diplomacy",
                  "International Studies and Diplomacy",
                  "Languages and Linguistics",
                  "Law",
                  "Library and Information Science",
                  "Linguistics / Edo",
                  "Marine Engineering",
                  "Marketing",
                  "Mass Communication",
                  "Mathematics",
                  "Mathematics and Economics",
                  "Mechanical Engineering",
                  "Mechatronics Engineering",
                  "Medical Biochemistry",
                  "Medical Laboratory Science",
                  "Medicine and Surgery",
                  "Metallurgical and Material Engineering",
                  "Microbiology",
                  "Music",
                  "Nursing / Nursing Science",
                  "Optometry",
                  "Petroleum Engineering",
                  "Pharmacy",
                  "Philosophy",
                  "Physical Education",
                  "Physics",
                  "Physics / Industrial Physics",
                  "Physiology",
                  "Physiotherapy",
                  "Plant Science and Biotechnology",
                  "Political Science",
                  "Political Science and Public Administration",
                  "Production Engineering",
                  "Public Administration",
                  "Pure / Applied Mathematics",
                  "Quantity Surveying",
                  "Radiography",
                  "Religious Studies",
                  "Science Laboratory Technology",
                  "Secretarial Administration and Education",
                  "Secretarial Education",
                  "Social Works",
                  "Sociology and Anthropology",
                  "Soil Science",
                  "Special Education",
                  "Statistics",
                  "Structural Engineering",
                  "Surveying and Geo-Informatics",
                  "Taxation",
                  "Technical Education",
                  "Theatre Arts",
                  "Veterinary Medicine",
                  "Zoology",
                  "Linguistics and African Language",
                  "Plant Biology and Biotechnology",
                  "Education Psychology and Curriculum Studies",
                  "Doctor of Pharmacy",
                  "Industrial Engineering"



              ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
    {
    universityName: "FUT Akure",
    location: "Akure",
    type:"Federal",
    website: "https://futa.edu.ng",
    email: "centres@futa.edu.ng",
    phone: +2349066707545,
    address: "P.M.B. 704, Akure, Ondo State, Nigeria",
    programmes:[
                 "Agricultural Engineering",
                  "Agricultural Extension and Communication Technology",
                  "Animal Production and Health",
                  "Applied Geology",
                  "Applied Geophysics",
                  "Architecture",
                  "Bio-medical Technology",
                  "Biochemistry",
                  "Biology",
                  "Biotechnology",
                  "Building",
                  "Civil Engineering",
                  "Computer Engineering",
                  "Computer Science",
                  "Crop, Soil And Pest Management",
                  "Eco-Tourism and Wildlife Management",
                  "Electrical / Electronics Engineering",
                  "Estate Management",
                  "Fisheries And Aquaculture Technology",
                  "Food Science and Technology",
                  "Forestry and Wood Technology",
                  "Human Anatomy",
                  "Industrial And Production Engineering",
                  "Industrial Chemistry",
                  "Industrial Design",
                  "Industrial Mathematics",
                  "Information Systems",
                  "Information Technology",
                  "Marine Science And Technology",
                  "Mathematics",
                  "Mechanical Engineering",
                  "Metallurgical and Material Engineering",
                  "Meteorology",
                  "Meteorology",
                  "Microbiology",
                  "Mining Engineering",
                  "Physics",
                  "Physiology",
                  "Quantity Surveying",
                  "Remote Sensing And Geosciences Information System",
                  "Software Engineering",
                  "Statistics",
                  "Surveying and Geo-Informatics",
                  "Urban and Regional Planning",
                  "Information And Communication Technology",
                  "Agriculture and Resource Economics",
                  "Cyber Security"

              ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
     {
    universityName: "Bayero University Kano",
    location: "Kano",
    type:"Federal",
    website: "https://buk.edu.ng",
    email: "",
    phone: +2349066707545,
    address: "",
    programmes:[
                 "Accounting",
                  "Adult Education",
                  "Agricultural Economics and Extension",
                  "Agricultural Engineering",
                  "Agricultural Science and Education",
                  "Agriculture",
                  "Anatomy",
                  "Applied Biology",
                  "Arabic Studies",
                  "Architecture",
                  "Automotive Engineering",
                  "Banking and Finance",
                  "Biochemistry",
                  "Biological Science(s)",
                  "Biology",
                  "Botany",
                  "Business Administration",
                  "Chemical Engineering",
                  "Chemistry",
                  "Civil Engineering",
                  "Common and Islamic Law",
                  "Computer Engineering",
                  "Computer Science",
                  "Criminology",
                  "Dentistry And Dental Surgery",
                  "Early Childhood Education",
                  "Economics",
                  "Education and Arabic",
                  "Education and Biology",
                  "Education and Chemistry",
                  "Education and Economics",
                  "Education and English Language",
                  "Education and French",
                  "Education and Geography",
                  "Education and Hausa",
                  "Education and History",
                  "Education and Islamic Studies",
                  "Education and Mathematics",
                  "Education and Physics",
                  "Electrical Engineering",
                  "Electronics",
                  "English Language",
                  "Entrepreneurship",
                  "Environmental Management",
                  "Estate Management",
                  "Fisheries and Aquaculture",
                  "Food Science and Technology",
                  "Forensic Science",
                  "Forestry And Wildlife Management",
                  "French",
                  "Geography",
                  "Geography",
                  "Geology",
                  "Hausa",
                  "Health Education",
                  "History",
                  "Industrial Chemistry",
                  "Information Science And Media Studies",
                  "Information Technology",
                  "International Relations",
                  "Islamic Studies",
                  "Library and Information Science",
                  "Linguistics",
                  "Mass Communication",
                  "Mathematics",
                  "Mechanical Engineering",
                  "Mechatronics Engineering",
                  "Medical Laboratory Science",
                  "Medicine and Surgery",
                  "Meteorology",
                  "Microbiology",
                  "Nursing / Nursing Science",
                  "Nutrition and Dietetics",
                  "Optometry",
                  "Petroleum Engineering",
                  "Pharmacy",
                  "Physical Education",
                  "Physical and Health Education",
                  "Physics",
                  "Physiology",
                  "Physiotherapy",
                  "Plant Biology",
                  "Political Science",
                  "Primary Education Studies",
                  "Public Administration",
                  "Quantity Surveying",
                  "Radiography",
                  "Sociology",
                  "Software Engineering",
                  "Special Education",
                  "Statistics",
                  "Taxation",
                  "Teacher Education Science",
                  "Technical Education",
                  "Telecommuniction Engineering",
                  "Theatre And Performing Arts",
                  "Urban and Regional Planning",
                  "Veterinary Medicine",
                  "Zoology",
                  "Environmental Health Science",
                  "Cyber Security"

              ],
requirements:   [            
                "Minimum JAMB score of 200, but actual cut‑off marks differ by Faculty and Programme",
                "Five (5) credits at one sitting or six (6) credits at two sittings in relevant subjects including Mathematics and English language.",
                "For Direct Entry Admission:",
                "Candidates must select UTME subject combinations specific to their chosen programme.",
                "Two (2) A‑level passes in subject(s) aligned to the intended programme or A relevant OND/HND/NCE(with at least Lower Credit) in related fields",
                "The same O’level credits required of UTME candidates (five/six credits including English, Mathematics as applicable)",
                ],
    notes: ""
  },
]

export default university
